services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database servlets_db;' -U postgres
  - psql -c 'CREATE TABLE IF NOT EXISTS users(id integer PRIMARY KEY, user_name varchar(30), login varchar(30), email varchar(30), password varchar(20), createDate date, role varchar(5));' -U postgres

# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту whiterabbit.nsk@gmail.com если сборка упала
notifications:
  email:
    recipients:
      -mailto: whiterabbit.nsk@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
